linters:
  enable:
    - errcheck # Check for unchecked errors
    - goimports # Check import formatting and add missing imports
    - gosimple # Simplify code
    - govet # Detect suspicious constructs
    - ineffassign # Detect unused assignments
    - staticcheck # Go static analysis
    - typecheck # Type-check Go code
    - unused # Check for unused constants, variables, functions and types
    - revive # Fast, configurable, extendable, flexible linter for Go
    - misspell # Find commonly misspelled English words
    - gofmt # Check if code was gofmt-ed

linters-settings:
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
        disabled: true
  staticcheck:
    checks:
      - all
      # Disable the SA1019 warning for grpc.DialContext which is deprecated
      - "-SA1019"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  exclude-dirs:
    - bin

run:
  timeout: 2m
